<?php
declare(strict_types=1);

// Simple WireGuard -> MikroTik RouterOS converter page (PHP 8)

function normalizeKey(string $key): string {
    return strtolower(trim($key));
}

function cleanValue(string $val): string {
    $val = trim($val);
    if ((str_starts_with($val, '"') && str_ends_with($val, '"')) || (str_starts_with($val, "'") && str_ends_with($val, "'"))) {
        $val = substr($val, 1, -1);
    }
    return trim($val);
}

function parseList(string $val): array {
    $parts = array_map(fn($x) => trim($x), preg_split('/\s*,\s*/', $val));
    return array_values(array_filter($parts, fn($x) => $x !== ''));
}

function parseEndpoint(string $val): array {
    $val = trim($val);
    if (preg_match('/^\[([^\]]+)\]:(\d+)$/', $val, $m)) {
        return ['address' => $m[1], 'port' => (int)$m[2]];
    }
    if (preg_match('/^(.+?):(\d+)$/', $val, $m)) {
        return ['address' => trim($m[1]), 'port' => (int)$m[2]];
    }
    return ['address' => $val, 'port' => null];
}

function parseWireGuardConfig(string $text): array {
    $lines = preg_split('/\r\n|\n|\r/', $text);
    $current = null;
    $result = [
        'interface' => [],
        'peers' => [],
    ];
    foreach ($lines as $rawLine) {
        $line = trim($rawLine);
        if ($line === '' || str_starts_with($line, '#') || str_starts_with($line, ';')) {
            continue;
        }
        if (preg_match('/^\[(.+)\]$/', $line, $m)) {
            $current = strtolower(trim($m[1]));
            if ($current === 'peer') {
                $result['peers'][] = [];
            }
            continue;
        }
        if (strpos($line, '=') !== false) {
            [$k, $v] = array_map('trim', explode('=', $line, 2));
            $key = normalizeKey($k);
            $value = cleanValue($v);

            if ($current === 'interface') {
                switch ($key) {
                    case 'address':
                        $result['interface']['address'] = parseList($value);
                        break;
                    case 'privatekey':
                        $result['interface']['privatekey'] = $value;
                        break;
                    case 'listenport':
                        $result['interface']['listenport'] = (int)$value;
                        break;
                    case 'dns':
                        $result['interface']['dns'] = parseList($value);
                        break;
                    case 'mtu':
                        $result['interface']['mtu'] = (int)$value;
                        break;
                    default:
                        $result['interface'][$key] = $value;
                        break;
                }
            } elseif ($current === 'peer') {
                $idx = max(count($result['peers']) - 1, 0);
                switch ($key) {
                    case 'publickey':
                        $result['peers'][$idx]['publickey'] = $value;
                        break;
                    case 'presharedkey':
                        $result['peers'][$idx]['presharedkey'] = $value;
                        break;
                    case 'allowedips':
                        $result['peers'][$idx]['allowedips'] = parseList($value);
                        break;
                    case 'endpoint':
                        $result['peers'][$idx]['endpoint'] = parseEndpoint($value);
                        break;
                    case 'persistentkeepalive':
                        $result['peers'][$idx]['persistentkeepalive'] = (int)$value;
                        break;
                    default:
                        $result['peers'][$idx][$key] = $value;
                        break;
                }
            }
        }
    }
    return $result;
}

function generateRouterOS(array $wg, string $ifName = 'wg0'): string {
    $lines = [];
    $iface = $wg['interface'] ?? [];
    $listen = isset($iface['listenport']) ? (int)$iface['listenport'] : null;
    $priv = $iface['privatekey'] ?? null;
    $lines[] = '/interface wireguard add name=' . $ifName . ' comment="Generated by WG-to-MikroTik"' 
        . ($listen ? ' listen-port=' . $listen : '')
        . ($priv ? ' private-key="' . $priv . '"' : '');

    $addresses = $iface['address'] ?? [];
    foreach ($addresses as $addr) {
        $lines[] = '/ip address add address=' . $addr . ' interface=' . $ifName;
    }

    $i = 1;
    foreach ($wg['peers'] as $peer) {
        $cmd = '/interface wireguard peers add interface=' . $ifName;
        if (!empty($peer['publickey'])) {
            $cmd .= ' public-key="' . $peer['publickey'] . '"';
        }
        if (!empty($peer['presharedkey'])) {
            $cmd .= ' preshared-key="' . $peer['presharedkey'] . '"';
        }
        if (!empty($peer['allowedips'])) {
            $cmd .= ' allowed-address=' . implode(',', $peer['allowedips']);
        }
        if (!empty($peer['endpoint']['address'])) {
            $cmd .= ' endpoint-address=' . $peer['endpoint']['address'];
            if (!empty($peer['endpoint']['port'])) {
                $cmd .= ' endpoint-port=' . (int)$peer['endpoint']['port'];
            }
        }
        if (!empty($peer['persistentkeepalive'])) {
            $cmd .= ' persistent-keepalive=' . (int)$peer['persistentkeepalive'];
        }
        $cmd .= ' comment="peer-' . $i . '"';
        $lines[] = $cmd;
        $i++;
    }

    return implode("\n", $lines) . "\n";
}

$error = null;
$output = null;
$savedFile = null;
$defaultIfName = 'wg0';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $ifName = isset($_POST['if_name']) && $_POST['if_name'] !== '' ? preg_replace('/[^A-Za-z0-9_-]/', '', $_POST['if_name']) : $defaultIfName;
    $sourceType = $_POST['source_type'] ?? 'text';
    $raw = '';

    if ($sourceType === 'file') {
        if (!isset($_FILES['wg_file']) || $_FILES['wg_file']['error'] !== UPLOAD_ERR_OK) {
            $error = 'Помилка завантаження файлу.';
        } else {
            $size = (int)$_FILES['wg_file']['size'];
            if ($size > 2 * 1024 * 1024) {
                $error = 'Файл надто великий (макс 2MB).';
            } else {
                $raw = file_get_contents($_FILES['wg_file']['tmp_name']) ?: '';
            }
        }
    } else {
        $raw = (string)($_POST['wg_text'] ?? '');
    }

    if (!$error) {
        $raw = trim($raw);
        if ($raw === '') {
            $error = 'Порожній вхідний конфіг.';
        } else {
            $wg = parseWireGuardConfig($raw);
            $output = generateRouterOS($wg, $ifName);

            $baseName = 'wg2mt-' . date('Ymd-His');
            $fileName = $baseName . '.rsc';
            $dir = __DIR__ . DIRECTORY_SEPARATOR . 'generated';
            if (!is_dir($dir)) {
                @mkdir($dir, 0777, true);
            }
            $dest = $dir . DIRECTORY_SEPARATOR . $fileName;
            if (@file_put_contents($dest, $output) !== false) {
                $savedFile = 'generated/' . $fileName;
            } else {
                $error = 'Не вдалося зберегти файл конфігурації.';
            }
        }
    }
}

function h(string $s): string { return htmlspecialchars($s, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }
?>
<!doctype html>
<html lang="uk">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>WireGuard → MikroTik (RouterOS) Конвертер</title>
    <style>
        body { font-family: system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif; margin: 24px; background: #f7f7fb; color: #222; }
        h1 { font-size: 22px; margin-bottom: 8px; }
        .card { background: #fff; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin-bottom: 16px; }
        label { display: block; margin: 8px 0 4px; font-weight: 600; }
        input[type="text"], textarea, select { width: 100%; padding: 8px; border: 1px solid #d1d5db; border-radius: 6px; background: #fff; }
        textarea { min-height: 160px; font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace; }
        .row { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
        .btn { display: inline-block; padding: 10px 16px; border-radius: 6px; background: #2563eb; color: #fff; border: none; cursor: pointer; font-weight: 600; }
        .btn:disabled { opacity: 0.6; cursor: not-allowed; }
        .muted { color: #6b7280; font-size: 13px; }
        .error { color: #b91c1c; font-weight: 600; }
        pre { background: #0b1020; color: #e6edf3; padding: 12px; border-radius: 8px; overflow: auto; }
        a.download { display: inline-block; margin-top: 8px; }
    </style>
</head>
<body>
<h1>WireGuard → MikroTik (RouterOS) Конвертер</h1>
<p class="muted">Імпортуйте конфіг WireGuard та отримайте .rsc для RouterOS. Файл буде збережено в папці скрипта (generated/).</p>

<div class="card">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div>
                <label for="if_name">Назва інтерфейсу RouterOS</label>
                <input type="text" id="if_name" name="if_name" value="<?= h($_POST['if_name'] ?? $defaultIfName) ?>" placeholder="wg0">
                <div class="muted">За замовчуванням: <code>wg0</code>. Можете змінити за потреби.</div>
            </div>
            <div>
                <label for="source_type">Джерело конфігу</label>
                <select id="source_type" name="source_type" onchange="toggleSource(this.value)">
                    <option value="text" <?= (($_POST['source_type'] ?? 'text') === 'text') ? 'selected' : '' ?>>Текст</option>
                    <option value="file" <?= (($_POST['source_type'] ?? '') === 'file') ? 'selected' : '' ?>>Файл</option>
                </select>
            </div>
        </div>

        <div id="source_text" style="margin-top: 12px; display: <?= (($_POST['source_type'] ?? 'text') === 'text') ? 'block' : 'none' ?>;">
            <label for="wg_text">Текстовий конфіг WireGuard</label>
            <textarea id="wg_text" name="wg_text" placeholder="[Interface]\nAddress = 10.0.0.1/24\nPrivateKey = ...\nListenPort = 51820\n\n[Peer]\nPublicKey = ...\nAllowedIPs = 10.0.0.2/32\nEndpoint = example.com:51820\nPersistentKeepalive = 25"><?= h($_POST['wg_text'] ?? '') ?></textarea>
        </div>

        <div id="source_file" style="margin-top: 12px; display: <?= (($_POST['source_type'] ?? '') === 'file') ? 'block' : 'none' ?>;">
            <label for="wg_file">Файл конфігурації WireGuard (.conf)</label>
            <input type="file" id="wg_file" name="wg_file" accept=".conf,text/plain">
        </div>

        <div style="margin-top: 16px;">
            <button type="submit" class="btn">Конвертувати</button>
        </div>
    </form>
</div>

<?php if ($error): ?>
    <div class="card"><div class="error"><?= h($error) ?></div></div>
<?php endif; ?>

<?php if ($output && !$error): ?>
    <div class="card">
        <h2 style="font-size:18px;margin:0 0 8px;">Згенерована конфігурація RouterOS</h2>
        <pre><?= h($output) ?></pre>
        <?php if ($savedFile): ?>
            <a class="download" href="<?= h($savedFile) ?>" download>Завантажити файл: <?= h(basename($savedFile)) ?></a>
        <?php endif; ?>
        <p class="muted">Імпорт в MikroTik: <code>import file-name=<?= h($savedFile ? basename($savedFile) : 'generated_file.rsc') ?></code> або перетягніть файл у Files.</p>
    </div>
<?php endif; ?>

<script>
function toggleSource(val) {
    document.getElementById('source_text').style.display = val === 'text' ? 'block' : 'none';
    document.getElementById('source_file').style.display = val === 'file' ? 'block' : 'none';
}
</script>
</body>
</html>